language: node_js
sudo: required
os:
- linux
- osx
node_js:
- '7'
before_install:
- openssl aes-256-cbc -K $encrypted_34c54a7b8ae9_key -iv $encrypted_34c54a7b8ae9_iv
  -in build/certs.p12.enc -out build/certs.p12 -d
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
addons:
  apt:
    packages:
    - xvfb
before_script:
- node --version
- npm install
- npm install -g electron
- node --version
- npm run package-ci
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
install:
- nvm install 7
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
dist: trusty
env:
  global:
  - secure: W9K9L/BdZZtUux/j08Ro0rrejtwCwV9q4PkLJy4Zgi88OHUIte5PbuQEbVveAxrECclkE7zcWUTM8h6Q9/ZDbeEGZkd79Dp3tVVqC03OAJDRHjTMmtAMVmIt+/TCBM6uYFUM710Rm1pHLWCjr5eOj4MLOMcEJEXjzOXbYkQT2DROD+fCxxxHXTzdBgtTceEMRJi4ZtbOf7tOhcHH0EaydPRk7W6cizxL6EB6Xlvm18gHwHbcQrsHphsdqfDV7liwFtQlI1AhcoyjRSwQt4k1+XifNzUOGC4Eorjq7yRB1dbtRciQRNp1MEuxSO8CGXZVtdymKWn5TnuAU9e9BWuSQgyvRzbC3R+fOoRT89gV901aXgLmowbEjwZPNyBPgYo6VipLqwAcuNPtv/bIyKW53eimpc+pwKsjv5ghD3wi4KIYLZfhU4eM+qSlz2bZq/2h2fq0FRONZDlj1+uqliXAfr7cdjNj/SnH0RVNAfiOX3dovcjhon+Hnq07sNP+KixsGVyzh5CWVe6IKoPb/QiBlB6XmgUwtkubVcxmv2aDXOUr9MXDC7k9zgG9EqjCRzSPeEwBXu64/gIsM1m7+X8pgaPeYOp1dZwH3oVDtcMrUt518+JH68mER+fI4Bsy8Uphr/+suOejz4K94enC7N+pdTemJw+AsOXUciYRrDk9LyQ=
  - secure: EdNNhy+PlWiatbtZlpIExS1eaMuOzl1/4Gj2rn6X1yQoT3D7jY9wFKrEMPvQVIOYPrgVpXilU2X9oyJDjIHUo8ZZQUS/WbhzVmjXxXZe3prDCQMzrddXCzBoN0cepInO8Sls8KUO2Vm/3bcy/F/Seyf02kxuLtAurGNdV0iXqMDykylntQDTn4zY7+27qUKzSf6ZZnqxheLBNS6YsQwb2rfmq/BGxuw1giRW6m+TbMYKRIGOYfLjsImyUnxZdKJjN3W0PZ6ZWhvWPdgUlM2T/dE7R1O/VOVPQpirfDKbqAWrpTwWKQ2cvLyrDDJQ36Hnv4co2wB4XcYeTAyL3J9B9SLIG8o54IfpqKcl3IJOiUBNOl4Ou+FUef3ZWvfUjdZL6zeUF3Xz3JMzSr1Zo+/LWeVaw1C4qvwLXIcp8F4+e2j0/pQi3D6y99seBmJit43Tx318H+JKgS+i2qbxIYiE0o6tf9ZXqqFjaufYLJJANN/7gWPdYvdxcY8BWO7sri/68z2M+qJb94zTZ1KqtRJrxr8p31xvEa4Z8T8bCss8DVJ+5kyTwzmXoQSnv/Th1OTZbzohkZgCUw15cxbdi2foDTNFMj0glSCuEJ9L1tkLzPzab6ChNmK8LuSIYvWotopKrjKDXXl6D+UxynwdmJxbuuhtobmHFOr754ppY9EH9DM=
  - secure: 2FVDOR/HHRrlW4ssZBcxbs9gdKfjdlR8xi32O/NDa7TX4EhG4YZWl/ClJyEybbnybdrFUISH28pcEx5svYVBCgtLznTAAqu9P10M+k4JU1ha2HA2MopIfGKWrbx+4rl9aUybDjF0PFl98UJRwVNkjr7wRhZqj9dxRD3zlYgrNxf8lJLwf2BHummNMJ+RTJRPSLhNRgL0lSQnHWay6FYzP9DAB7TI0HQaaPca44iwE3RlyZMus1i12Aw0tOV17ib5PFJQZui+KtnunpePJv5iTspMcK3xDsVNyjD0fDtsA+A7pLJM7244xbaCLDlxAjZ+MWX91XUrq8cHbbhMqEpvR0WC02TxSl4RU7JjohJvtcy5Uw2SKn6GFTpgS9aq62ELgMmPcYQn/qKeSwI9SnUSUP96fdc1UVNd04clFyQ8+yE/9J0Du995mzzYBDSPKm/9sXZBkJ4j2sl5wIyaiMEc4BIQa7V7tvDV7Lq9I+msjB6GST9TzjRzSZ/g0xS/D2HgeE8i72fDoz8XBVqL/INndnF9QVsx5vXjTSScvZgP5fRzOxscZjbY7OGLQxenBqtck1u0/IDys+ym4kjZTnspZ9fWW/PY8498Nko9dIV8UAa2Tnc/QCApgBfJaqcIx3shzMiebI2punlhQ5aDRopmK8iU4GOQZDHlqjs5v5Oy/t4=
